# Generated by Django 3.1.7 on 2021-04-09 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_productimage_image_id'),
        ('carts', '0008_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='productimage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productimage'),
            preserve_default=False,
        ),
    ]
