# Generated by Django 3.1.7 on 2021-04-10 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_cartitem_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
