# Generated by Django 3.1.7 on 2021-04-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_remove_cartitem_user'),
        ('orders', '0007_remove_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carts.cartitem'),
            preserve_default=False,
        ),
    ]
