# Generated by Django 3.1.7 on 2021-04-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_remove_cartitem_user'),
        ('orders', '0008_order_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartitem',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='carts.cartitem'),
        ),
    ]
