# Generated by Django 3.1.7 on 2021-04-11 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_cart_user'),
        ('orders', '0012_remove_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.cartitem'),
        ),
    ]
