# Generated by Django 3.1.7 on 2021-04-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_cart_user'),
        ('orders', '0013_order_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartitem',
        ),
        migrations.AddField(
            model_name='order',
            name='cartitem',
            field=models.ManyToManyField(blank=True, null=True, to='carts.CartItem'),
        ),
    ]
