# Generated by Django 3.1.7 on 2021-04-12 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0014_auto_20210412_0534'),
        ('orders', '0014_auto_20210412_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartitem',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='carts.cart'),
            preserve_default=False,
        ),
    ]
