# Generated by Django 3.1.7 on 2021-04-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210319_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_id',
            field=models.IntegerField(default=1010),
        ),
    ]
