# Generated by Django 3.1.7 on 2021-04-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productimage_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_id',
        ),
    ]
