# Generated by Django 3.1.7 on 2021-04-16 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210414_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='height',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='length',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='width',
        ),
    ]
