# Generated by Django 3.1.7 on 2021-04-16 03:19

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210416_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=60, populate_from=('title', 'created'), unique=True, verbose_name='slug'),
        ),
    ]
