# Generated by Django 3.1.7 on 2021-04-17 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210416_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='variations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariation'),
        ),
    ]
